language: php

sudo: false

matrix:
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
      env: COVERAGE=yes
    - php: hhvm
    - php: nightly
  allow_failures:
    - php: hhvm
    - php: nightly

install:
  - composer install

script:
  - if [[ $TRAVIS_PHP_VERSION == 5.4 ]]; then vendor/bin/phpcs --standard=psr2 -np src; fi
  - if [[ $COVERAGE == yes ]]; then phpunit --coverage-text --coverage-clover=coverage.clover; else phpunit; fi

after_script:
  - if [[ $COVERAGE == yes ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

notifications:
  email: false
