name: Tests

on:
  push:
    branches:
      - master
      - v2.0
  pull_request:
    branches:
      - master
      - v2.0

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install PHP_CodeSniffer
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          php phpcs.phar --version
      - name: Check coding style
        run: |
          php phpcs.phar --standard=PSR2 -p src

  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php: '7.2'
            phpunit: '7.5.20'
          - php: '7.3'
            phpunit: '7.5.20'
          - php: '7.4'
            phpunit: '7.5.20'
          - php: '8.0'
            phpunit: '8.5.13'
          - php: '8.1'
            phpunit: '10'
          - php: '8.2'
            phpunit: '10'

    name: PHP ${{ matrix.php }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: php-actions/composer@v5
        with:
          php_version: ${{ matrix.php }}
      - name: PHPUnit tests
        uses: php-actions/phpunit@v2
        with:
          version: ${{ matrix.phpunit }}
          php_version: ${{ matrix.php }}
          configuration: phpunit.dist.xml
          memory_limit: 256M
